### ISSUE TITLE
Mod incompatile with newest AE2 Version

### ISSUE THREAD

**Issue by Chaosdave34** [Tfarcenim/AE2WirelessTerminalLibrary#22] opened 2021-07-03 11:36 UTC
The Mod seems incompatile with newest AE2 Version (I think from beginning june). Will there be an update to fix it?

**Comment by SilverScreamBr** [comment] 2021-07-24 12:34
Please update this on curse

**Comment by Tfarcenim** [comment] 2021-07-24 13:59
Duplicate of #16, it will be updated when I have the time, but unfortunately paid work comes first as I still have bills.

**Closed as completed by Tfarcenim** 2021-07-24 13:59 UTC
