### ISSUE TITLE
Server startup crash with the latest ae2wtlib and stable AE-2 8.3.1

### ISSUE THREAD

**Issue by starmun-0010** [Tfarcenim/AE2WirelessTerminalLibrary#9] opened 2021-05-24 06:49 UTC
**Versions**
**Minecraft:** 1.16.5
**Forge:** 36.1.18
**AE2:** appliedenergistics2-8.3.1
**AE2WT:** ae2wtlib-0.0c-1.16.5

**To Reproduce**

- Setup forge server
- Install AE2 Stable release
- Install Applied Energistics 2 Wireless Terminals Forge
- Start Server

**Crash Report**
[crash-2021-05-24_11.40.10-fml.txt](https://github.com/Tfarcenim/AE2WirelessTerminalLibrary/files/6530351/crash-2021-05-24_11.40.10-fml.txt)

**Comment by Tfarcenim** [comment] 2021-05-31 16:03
duplicate of #7

**Closed as completed by Tfarcenim** 2021-05-31 16:03 UTC
Labels: duplicate
